[package]
name = "ue4ssl-support"
edition.workspace = true
version.workspace = true
publish.workspace = true
build = "build.rs"
links = "ue4ssl_support"

[lib]
path = "src/lib.rs"
crate-type = ["rlib", "staticlib"]

[dependencies]
ue4ssl_abi.workspace = true

[build-dependencies]
cc.workspace = true
ue4ssl_abi.workspace = true
