[workspace]
resolver = "2"
members = [
    "crates/xtask",
    "crates/ue4ssl-abi",
    "crates/ue4ssl-unreal-support",
    "crates/ue4ssl-object-searcher",
    "crates/ue4ssl-support",
    "crates/ue4ssl-javascript-support",
    "crates/ue4ssl-lua-support",
    "crates/ue4ssl-runtime",
    "crates/ue4ssl-dll",
    "crates/ue4ssl-javascript",
    "crates/ue4ssl-lua",
    "crates/ue4ssl-paksync",
    "crates/ue4ssl-proxy",
    "crates/patternsleuth",
    "crates/patternsleuth-scanner",
    "crates/patternsleuth-bind",
    "crates/ue4ssl-hook",
    "crates/ue4ssl-mod-build",
]
default-members = [
    "crates/ue4ssl-dll",
]

[workspace.package]
edition = "2021"
version = "0.1.0"
publish = false

[workspace.dependencies]
anyhow = "1.0.95"
camino = "1.1.9"
cc = { version = "1.2.7", features = ["parallel"] }
clap = { version = "4.5.23", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
xshell = "0.2.7"
iced-x86 = "1.20.0"
itertools = "0.12.0"
memchr = "2.7.1"
msvc-demangler = "0.9.0"
object = "0.32.2"
pdb = "0.8.0"
rayon = "1.8.0"
strum = { version = "0.25.0", features = ["strum_macros", "derive"] }
windows = "0.52.0"

ue4ssl_abi = { path = "crates/ue4ssl-abi" }
ue4ssl-runtime = { path = "crates/ue4ssl-runtime" }
ue4ssl-unreal-support = { path = "crates/ue4ssl-unreal-support" }
ue4ssl-object-searcher = { path = "crates/ue4ssl-object-searcher" }
ue4ssl-support = { path = "crates/ue4ssl-support" }
ue4ssl-hook = { path = "crates/ue4ssl-hook" }
patternsleuth = { path = "crates/patternsleuth", features = ["process-internal", "image-pe"] }
patternsleuth_scanner = { path = "crates/patternsleuth-scanner" }
patternsleuth_bind = { path = "crates/patternsleuth-bind" }

[profile.dev]
debug = true
incremental = true

[profile.release]
debug = true
incremental = true
lto = "thin"
codegen-units = 1
