[package]
name = "ue4ssl-dll"
edition.workspace = true
version.workspace = true
publish.workspace = true

[lib]
name = "UE4SSL"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
ue4ssl_abi.workspace = true
ue4ssl-runtime.workspace = true
ue4ssl-hook.workspace = true
patternsleuth_bind.workspace = true
ue4ssl-unreal-support.workspace = true
ue4ssl-object-searcher.workspace = true
ue4ssl-platform.workspace = true

[build-dependencies]
cc.workspace = true
ue4ssl-build.workspace = true
